### ISSUE TITLE
Doesn't handle SIGTERM well

### ISSUE THREAD

**Issue by LukeShu** [datawire/teleproxy#37]
I'm not sure what's going on with cleanup, but when I send teleproxy SIGTERM, it starts to gracefully quit, but it gets SIGSEGV between the last line in `main()` running and the program exiting.

Here's an example of `telepresence outbound` output, when I run `killall teleproxy` while it's running:

```
T: Background process (teleproxy intercept) exited with return code 2. Command was:
T:   sudo teleproxy -mode intercept

T: Recent output was:
T:   2018/12/18 23:02:23 TPY: Final rlimit {49152 49152}
T:   2018/12/18 23:02:23 TPY: Error: Proxy: listen tcp :1234: bind: address already in use
T:   2018/12/18 23:04:22 TPY: terminated
T:   panic: runtime error: invalid memory address or nil pointer dereference
T:   [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x40592d8]
T:
T:   goroutine 1 [running]:
T:   main.main()
T:         /Users/admin/src/teleproxy/.go-workspace/src/github.com/datawire/teleproxy/cmd/teleproxy/teleproxy.go:103 +0x505
```

The line `teleproxy.go:103` is the closing brace at the end of the `main()` function.

**Comment by LukeShu** [comment]
This seems to be resolved?
