### ISSUE TITLE
teleproxy DNS does not work with systemd-resolved

### ISSUE THREAD

**Issue by LukeShu** [datawire/teleproxy#90]
Even with resolved caching disabled.  IDK why.

**Comment by ark3** [comment]
Is this related to llmnr stuff? https://github.com/telepresenceio/telepresence/issues/242

**Comment by LukeShu** [comment]
I don't think so? The docs linked there note that resolved only uses LLMNR for single-label lookups. I tested with both singe-lable(+search-path) names and qualified names.  If I understand  telepresenceio/telepresence#242 correctly, it's only a problem for single-label lookups.

But I'll try fiddling with LLMNR stuff to verify that.

**Comment by ark3** [comment]
Perhaps start by clarifying what "does not work" means.

**Comment by LukeShu** [comment]
Yeah, I should. I created the issue quickly mostly so I wouldn't forget that it was an issue.

**Comment by LukeShu** [comment]
I've misremembered.  Now, it does look like the LLMNR thing.

Actual write-up, not based on my hazy memory:

# The problem is observed
```
$ make proxy
sudo rm -f build-aux/teleproxy
curl -o build-aux/teleproxy https://s3.amazonaws.com/datawire-static-files/teleproxy/0.3.16/linux/amd64/teleproxy
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 36.3M  100 36.3M    0     0  57.0M      0 --:--:-- --:--:-- --:--:-- 57.0M
sudo chown root build-aux/teleproxy
sudo chmod go-w,a+sx build-aux/teleproxy
if ! curl -sk https://kubernetes/api/; then \
	build-aux/teleproxy > build-aux/teleproxy.log 2>&1 & \
fi
Checking proxy (1): https://kubernetes/api/
…
Checking proxy (32): https://kubernetes/api/
^Cmake: *** [build-aux/teleproxy.mk:39: proxy] Interrupt
```
```
$ cat build-aux/teleproxy.log 
2019/04/16 15:38:04 TPY: Automatically set -dns=172.31.0.2
2019/04/16 15:38:04 TPY: Automatically set -fallback=172.31.0.2
2019/04/16 15:38:04 TPY: initial rlimit: {1024 524288}
2019/04/16 15:38:04 TPY: Final rlimit {999999 999999}
2019/04/16 15:38:04 DNS: listening on 127.0.0.1:1233
2019/04/16 15:38:04 DNS: listening on 172.17.0.1:1233
2019/04/16 15:38:04 PXY: listening limit=10000
2019/04/16 15:38:04 NAT: iptables -t nat -D OUTPUT -j teleproxy
2019/04/16 15:38:04 NAT: iptables v1.8.2 (legacy): Couldn't load target `teleproxy':No such file or directory
2019/04/16 15:38:04 NAT: 
2019/04/16 15:38:04 NAT: Try `iptables -h' or 'iptables --help' for more information.
2019/04/16 15:38:04 NAT: exit status 2
2019/04/16 15:38:04 NAT: iptables -t nat -D PREROUTING -j teleproxy
2019/04/16 15:38:04 NAT: iptables v1.8.2 (legacy): Couldn't load target `teleproxy':No such file or directory
2019/04/16 15:38:04 NAT: 
2019/04/16 15:38:04 NAT: Try `iptables -h' or 'iptables --help' for more information.
2019/04/16 15:38:04 NAT: exit status 2
2019/04/16 15:38:04 NAT: iptables -t nat -N teleproxy
2019/04/16 15:38:04 NAT: iptables -t nat -F teleproxy
2019/04/16 15:38:04 NAT: iptables -t nat -I OUTPUT 1 -j teleproxy
2019/04/16 15:38:04 NAT: iptables -t nat -I PREROUTING 1 -j teleproxy
2019/04/16 15:38:04 NAT: iptables -t nat -A teleproxy -j RETURN --dest 127.0.0.1/32 -p tcp
2019/04/16 15:38:04 NAT: iptables -t nat -A teleproxy -j REDIRECT --dest 172.31.0.2/32 -p udp --to-ports 1233
2019/04/16 15:38:04 NAT: iptables -t nat -A teleproxy -j REDIRECT --dest 127.254.254.254/32 -p tcp --to-ports 42307
2019/04/16 15:38:04 INT: STORE teleproxy.->{teleproxy 127.254.254.254 tcp 42307 }
2019/04/16 15:38:04 KAP: kubectl --context admin@kubernetes --namespace default apply -f -
2019/04/16 15:38:05 KAP: pod/teleproxy created
2019/04/16 15:38:05 BRG: kubernetes ctx=admin@kubernetes ns=default
2019/04/16 15:38:05 KPF: kubectl --context admin@kubernetes --namespace default port-forward pod/teleproxy 8022
2019/04/16 15:38:05 SSH: ssh -D localhost:1080 -C -N -oConnectTimeout=5 -oExitOnForwardFailure=yes -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null telepresence@localhost -p 8022
2019/04/16 15:38:05 SSH: ssh: connect to host localhost port 8022: Connection refused
2019/04/16 15:38:05 SSH: exit status 255
2019/04/16 15:38:05 SSH: ssh restarting...
2019/04/16 15:38:05 SSH: sh -c 
2019/04/16 15:38:05 KPF: error: unable to forward port because pod is not running. Current status=Pending
2019/04/16 15:38:05 KPF: exit status 1
2019/04/16 15:38:05 KPF: kubectl restarting...
2019/04/16 15:38:05 KPF: sh -c kubectl --context admin@kubernetes --namespace default get pod/teleproxy
2019/04/16 15:38:05 KPF: NAME        READY   STATUS              RESTARTS   AGE
2019/04/16 15:38:05 KPF: teleproxy   0/1     ContainerCreating   0          0s
2019/04/16 15:38:05 BRG: error posting update to kubernetes: Post http://teleproxy/api/tables/: dial tcp: lookup teleproxy: no such host
2019/04/16 15:38:05 BRG: Setting DNS search path: default.svc.cluster.local.
2019/04/16 15:38:06 SSH: ssh -D localhost:1080 -C -N -oConnectTimeout=5 -oExitOnForwardFailure=yes -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null telepresence@localhost -p 8022
2019/04/16 15:38:06 SSH: ssh: connect to host localhost port 8022: Connection refused
2019/04/16 15:38:06 SSH: exit status 255
2019/04/16 15:38:06 SSH: ssh restarting...
2019/04/16 15:38:06 SSH: sh -c 
2019/04/16 15:38:06 KPF: kubectl --context admin@kubernetes --namespace default port-forward pod/teleproxy 8022
2019/04/16 15:38:06 KPF: error: unable to forward port because pod is not running. Current status=Pending
2019/04/16 15:38:06 KPF: exit status 1
2019/04/16 15:38:06 KPF: kubectl restarting...
2019/04/16 15:38:06 KPF: sh -c kubectl --context admin@kubernetes --namespace default get pod/teleproxy
2019/04/16 15:38:06 KPF: NAME        READY   STATUS              RESTARTS   AGE
2019/04/16 15:38:06 KPF: teleproxy   0/1     ContainerCreating   0          1s
2019/04/16 15:38:06 BRG: error setting up search path: Post http://teleproxy/api/search: dial tcp: lookup teleproxy: no such host
2019/04/16 15:38:06 NAT: iptables -t nat -D OUTPUT -j teleproxy
2019/04/16 15:38:06 NAT: iptables -t nat -D PREROUTING -j teleproxy
2019/04/16 15:38:06 NAT: iptables -t nat -F teleproxy
2019/04/16 15:38:06 NAT: iptables -t nat -X teleproxy
2019/04/16 15:38:06 DNS: flushing PIDS[]
panic: Post http://teleproxy/api/search: dial tcp: lookup teleproxy: no such host

goroutine 1 [running]:
main.bridges(0xc0004a6b40, 0x0)
	/home/circleci/go/src/github.com/datawire/teleproxy/cmd/teleproxy/teleproxy.go:294 +0x63a
main.main()
	/home/circleci/go/src/github.com/datawire/teleproxy/cmd/teleproxy/teleproxy.go:107 +0x4b1
```
# The workaround
```
$ sudo systemctl stop systemd-resolved
```
```
$ make proxy
if ! curl -sk https://kubernetes/api/; then \
	build-aux/teleproxy > build-aux/teleproxy.log 2>&1 & \
fi
Checking proxy (1): https://kubernetes/api/
Checking proxy (2): https://kubernetes/api/
Checking proxy (3): https://kubernetes/api/
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "10.10.49.26:6443"
    }
  ]
}

Proxy UP!
```
# More info
Versions:
```
$ pacman -Q systemd
systemd 241.0-2

$ ./build-aux/teleproxy --version
kubeapply version 0.3.16
```

Configuration:
```
$ cat /etc/nsswitch.conf 
# Name Service Switch configuration file.
# See nsswitch.conf(5) for details.

passwd: files mymachines systemd
group: files mymachines systemd
shadow: files

publickey: files

hosts: files mymachines myhostname resolve [!UNAVAIL=return] dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

netgroup: files
```
```
$ ls -l /etc/resolv.conf 
lrwxrwxrwx 1 root root 34 Feb 14 15:29 /etc/resolv.conf -> ../run/systemd/resolve/resolv.conf
```
```
$ cat /etc/resolv.conf 
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 172.31.0.2
search ec2.internal
```

**Comment by LukeShu** [comment]
When I wrote the above, I was under the mistaken belief that teleproxy was statically linked, and therefore was bypassing the NS switch, and using resolv.conf directly.  That is not the case; it is dynamically linked, and is therefore probably using the NS switch.
