### ISSUE TITLE
teleproxy doesn't work on macs with ipv6 enabled

### ISSUE THREAD

**Issue by rhs** [datawire/teleproxy#93]
```
2019/04/04 15:44:12 TPY: Automatically set -dns=2001:470:1f07:a68::1
2019/04/04 15:44:12 TPY: Automatically set -fallback=2001:470:1f07:a68::1
2019/04/04 15:44:12 TPY: initial rlimit: {7168 9223372036854775807}
2019/04/04 15:44:12 TPY: Final rlimit {49152 49152}
2019/04/04 15:44:12 DNS: listening on 127.0.0.1:1233
2019/04/04 15:44:12 PXY: listening limit=10000
2019/04/04 15:44:12 DNS: sh -c networksetup -listallnetworkservices | fgrep -v '*'
2019/04/04 15:44:12 DNS: Model 01
2019/04/04 15:44:12 DNS: Thunderbolt Ethernet Slot 2
2019/04/04 15:44:12 DNS: USB 10/100/1000 LAN
2019/04/04 15:44:12 DNS: iPhone USB
2019/04/04 15:44:12 DNS: Thunderbolt FireWire
2019/04/04 15:44:12 DNS: Wi-Fi
2019/04/04 15:44:12 DNS: Bluetooth PAN
2019/04/04 15:44:12 DNS: Thunderbolt Bridge
2019/04/04 15:44:12 DNS: sh -c networksetup -getsearchdomains 'Model 01'
2019/04/04 15:44:12 DNS: .
2019/04/04 15:44:12 DNS: sh -c networksetup -setsearchdomains 'Model 01' '.'
2019/04/04 15:44:12 DNS: sh -c networksetup -getsearchdomains 'Thunderbolt Ethernet Slot 2'
2019/04/04 15:44:12 DNS: .
2019/04/04 15:44:12 DNS: sh -c networksetup -setsearchdomains 'Thunderbolt Ethernet Slot 2' '.'
2019/04/04 15:44:12 DNS: sh -c networksetup -getsearchdomains 'USB 10/100/1000 LAN'
2019/04/04 15:44:12 DNS: .
2019/04/04 15:44:12 DNS: sh -c networksetup -setsearchdomains 'USB 10/100/1000 LAN' '.'
2019/04/04 15:44:12 DNS: sh -c networksetup -getsearchdomains 'iPhone USB'
2019/04/04 15:44:12 DNS: .
2019/04/04 15:44:12 DNS: sh -c networksetup -setsearchdomains 'iPhone USB' '.'
2019/04/04 15:44:13 DNS: sh -c networksetup -getsearchdomains 'Thunderbolt FireWire'
2019/04/04 15:44:13 DNS: .
2019/04/04 15:44:13 DNS: sh -c networksetup -setsearchdomains 'Thunderbolt FireWire' '.'
2019/04/04 15:44:13 DNS: sh -c networksetup -getsearchdomains 'Wi-Fi'
2019/04/04 15:44:13 DNS: .
2019/04/04 15:44:13 DNS: sh -c networksetup -setsearchdomains 'Wi-Fi' '.'
2019/04/04 15:44:13 DNS: sh -c networksetup -getsearchdomains 'Bluetooth PAN'
2019/04/04 15:44:13 DNS: .
2019/04/04 15:44:13 DNS: sh -c networksetup -setsearchdomains 'Bluetooth PAN' '.'
2019/04/04 15:44:13 DNS: sh -c networksetup -getsearchdomains 'Thunderbolt Bridge'
2019/04/04 15:44:13 DNS: .
2019/04/04 15:44:13 DNS: sh -c networksetup -setsearchdomains 'Thunderbolt Bridge' '.'
2019/04/04 15:44:13 pfctl -a teleproxy -F all < 
2019/04/04 15:44:13 No ALTQ support in kernel
ALTQ related functions disabled
rules cleared
nat cleared
dummynet cleared
0 tables deleted.
2019/04/04 15:44:13 pfctl -f /dev/stdin < pass on lo0
2019/04/04 15:44:13 pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
/dev/stdin:1: syntax error
pfctl: Syntax error in config file: pf rules not loaded
2019/04/04 15:44:13 exit status 1
2019/04/04 15:44:13 pfctl -a teleproxy -f /dev/stdin < pass out quick inet proto tcp to 127.0.0.1/32

2019/04/04 15:44:13 pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
2019/04/04 15:44:13 pfctl -a teleproxy -f /dev/stdin < rdr pass on lo0 inet proto udp to 2001:470:1f07:a68::1 -> 127.0.0.1 port 1233
pass out quick inet proto tcp to 127.0.0.1/32
pass out route-to lo0 inet proto udp to 2001:470:1f07:a68::1 keep state

2019/04/04 15:44:13 pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
/dev/stdin:1: rule expands to no valid combination
/dev/stdin:3: rule expands to no valid combination
pfctl: Syntax error in config file: pf rules not loaded
2019/04/04 15:44:13 exit status 1
2019/04/04 15:44:13 pfctl -a teleproxy -f /dev/stdin < rdr pass on lo0 inet proto tcp to 127.254.254.254 -> 127.0.0.1 port 58682
rdr pass on lo0 inet proto udp to 2001:470:1f07:a68::1 -> 127.0.0.1 port 1233
pass out quick inet proto tcp to 127.0.0.1/32
pass out route-to lo0 inet proto tcp to 127.254.254.254 keep state
pass out route-to lo0 inet proto udp to 2001:470:1f07:a68::1 keep state

2019/04/04 15:44:13 pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
/dev/stdin:2: rule expands to no valid combination
/dev/stdin:5: rule expands to no valid combination
pfctl: Syntax error in config file: pf rules not loaded
2019/04/04 15:44:13 exit status 1
2019/04/04 15:44:13 INT: STORE teleproxy.->{teleproxy 127.254.254.254 tcp 58682 }
2019/04/04 15:44:13 KAP: kubectl --kubeconfig /Users/flynn/.kube/kat-flynn.yaml --context admin@kubernetes --namespace default apply -f -
2019/04/04 15:44:14 KAP: pod/teleproxy unchanged
2019/04/04 15:44:14 BRG: kubernetes ctx=admin@kubernetes ns=default
2019/04/04 15:44:14 KPF: kubectl --kubeconfig /Users/flynn/.kube/kat-flynn.yaml --context admin@kubernetes --namespace default port-forward pod/teleproxy 8022
2019/04/04 15:44:14 SSH: ssh -D localhost:1080 -C -N -oConnectTimeout=5 -oExitOnForwardFailure=yes -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null telepresence@localhost -p 8022
2019/04/04 15:44:14 SSH: ssh: connect to host localhost port 8022: Connection refused
2019/04/04 15:44:14 SSH: exit status 255
2019/04/04 15:44:14 SSH: ssh restarting...
2019/04/04 15:44:14 SSH: sh -c 
2019/04/04 15:44:15 BRG: error posting update to kubernetes: Post http://teleproxy/api/tables/: dial tcp: lookup teleproxy: no such host
2019/04/04 15:44:15 BRG: Setting DNS search path: default.svc.cluster.local.
2019/04/04 15:44:15 BRG: error setting up search path: Post http://teleproxy/api/search: dial tcp: lookup teleproxy: no such host
2019/04/04 15:44:15 Removing rule: anchor teleproxy all
2019/04/04 15:44:15 Removing rule: rdr-anchor teleproxy all
2019/04/04 15:44:15 pfctl -a teleproxy -F all < 
2019/04/04 15:44:15 No ALTQ support in kernel
ALTQ related functions disabled
rules cleared
nat cleared
dummynet cleared
0 tables deleted.
2019/04/04 15:44:15 DNS: sh -c networksetup -setsearchdomains 'Model 01' '.'
2019/04/04 15:44:15 DNS: sh -c networksetup -setsearchdomains 'Thunderbolt Ethernet Slot 2' '.'
2019/04/04 15:44:15 DNS: sh -c networksetup -setsearchdomains 'USB 10/100/1000 LAN' '.'
2019/04/04 15:44:15 DNS: sh -c networksetup -setsearchdomains 'iPhone USB' '.'
2019/04/04 15:44:15 DNS: sh -c networksetup -setsearchdomains 'Thunderbolt FireWire' '.'
2019/04/04 15:44:15 DNS: sh -c networksetup -setsearchdomains 'Wi-Fi' '.'
2019/04/04 15:44:15 DNS: sh -c networksetup -setsearchdomains 'Bluetooth PAN' '.'
2019/04/04 15:44:15 KPF: Forwarding from [::1]:8022 -> 8022
2019/04/04 15:44:15 KPF: Forwarding from 127.0.0.1:8022 -> 8022
2019/04/04 15:44:15 DNS: sh -c networksetup -setsearchdomains 'Thunderbolt Bridge' '.'
2019/04/04 15:44:15 SSH: ssh -D localhost:1080 -C -N -oConnectTimeout=5 -oExitOnForwardFailure=yes -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null telepresence@localhost -p 8022
2019/04/04 15:44:15 KPF: Handling connection for 8022
2019/04/04 15:44:15 DNS: flushing PIDS[178]
panic: Post http://teleproxy/api/search: dial tcp: lookup teleproxy: no such host

goroutine 1 [running]:
main.bridges(0xc00046f700, 0x21)
	/Users/distiller/go/src/github.com/datawire/teleproxy/cmd/teleproxy/teleproxy.go:294 +0x63a
main.main()
	/Users/distiller/go/src/github.com/datawire/teleproxy/cmd/teleproxy/teleproxy.go:107 +0x4b1
```

**Comment by kflynn** [comment]
This is especially important on my Mac, which usually has at least one IPv6 nameserver.

Note also: _all_ V6 servers, not just the first one.
